modernize bash syntax, improve efficiency and fix include bugs
* Fixed array expansion syntax error in SOURCESTACK loop
* Resolved implicit global variable scoping for current manifest
* Replaced deprecated 'test' (-a) operators with modern '[[ ]]'
* Optimized performance by removing subshells and 'ls' parsing
* Standardized function names to snake_case

diff --git a/initial-manifest b/initial-manifest
--- a/initial-manifest
+++ b/initial-manifest
@@ -1,70 +1,83 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
 # Cdist initial manifest
 
 # Break on errors
 set -e
 
-MANIFESTALL=autorun
+MANIFESTALL="autorun"
 SOURCESTACK=()
+SOURCESTACKONCE=()
 
-CDISTSOURCE() {
-   man="$1"
-   if test "$CDISTDEBUG" -gt 0; then
+cdist_source() {
+   local man="$1"
+   if [[ "${CDISTDEBUG:-0}" -gt 0 ]]; then
       echo "INIT MANIFEST: sourcing $man"
       set -x
    fi
    . "$man"
-   if test "$CDISTDEBUG" -gt 0; then
+   if [[ "${CDISTDEBUG:-0}" -gt 0 ]]; then
       set +x
+      echo "INIT MANIFEST: done sourcing $man"
    fi
 }
 
 # Safe include function for manifests including other manifests
 include() {
    local i dir include_manifest=''
+   local target="$1"
+   local run_type="${2:-}"
+   local current_manifest="${BASH_SOURCE[1]:-unknown}"
 
-   test "$CDISTACTION" = "" -a -e "${__manifest}/${MANIFESTALL}/${1}" && return 0
+   if [[ -z "${CDISTACTION:-}" && -e "${__manifest}/${MANIFESTALL}/${target}" ]]; then
+      return 0
+   fi
 
-   if test $(basename "${1}") == $(basename "${__cdist_manifest}"); then
-      echo "ERROR: The init manifest itself cannot be included"
+   if [[ "${target##*/}" == "${__cdist_manifest##*/}" ]]; then
+      echo "ERROR: The init manifest itself cannot be included" >&2
       exit 1
    fi
 
-   for dir in ${__manifest}/ $(ls -d ${__manifest}/*/); do
-      if test -e "${dir}${1}"; then
-         include_manifest="${dir}${1}"
-         break
-      fi
-   done
+   if [[ -e "${__manifest}/${target}" ]]; then
+      include_manifest="${__manifest}/${target}"
+   else
+      for dir in "${__manifest}"/*/ ; do
+         if [[ -e "${dir}${target}" ]]; then
+            include_manifest="${dir}${target}"
+            break
+         fi
+      done
+   fi
 
-   if test "${2}" = 'once'; then
-      for i in "${SOURCESTACKONCE[@]}"; do
-         if test "${i}" == "${include_manifest}"; then
+   if [[ "${run_type}" == "once" ]]; then
+      for i in "${SOURCESTACKONCE[@]:-}"; do
+         if [[ "${i}" == "${include_manifest}" ]]; then
             return 0
          fi
       done
    fi
 
-   # reset SOURCESTACK when this function is called from a new manifest
-   if [[ ! " ${SOURCESTACK[*]} " =~ " ${manifest} " ]]; then
-      SOURCESTACK=("${manifest}")
+   # Reset SOURCESTACK when this function is called from a new manifest
+   if [[ ! " ${SOURCESTACK[*]:-} " =~ " ${current_manifest} " ]]; then
+      SOURCESTACK=("${current_manifest}")
    fi
 
-   for i in "${SOURCESTACK[@]}}"; do
-      if test "${i}" == "${include_manifest}"; then
-         read line func file < <(caller)
-         test -z "${file}" && file="${func}"
-         file=$(basename "${file}")
-         echo "ERROR: Circular/multiple include(s) of ${1} in manifest ${file}"
+   for i in "${SOURCESTACK[@]:-}"; do
+      if [[ "${i}" == "${include_manifest}" ]]; then
+         read -r line func file < <(caller)
+         [[ -z "${file:-}" ]] && file="${func}"
+         file="${file##*/}"
+         echo "ERROR: Circular/multiple include(s) of ${target} in manifest ${file}" >&2
          exit 1
       fi
    done
 
-   if ! test -z "${include_manifest}"; then
+   if [[ -n "${include_manifest}" ]]; then
       SOURCESTACK+=("${include_manifest}")
-      SOURCESTACKONCE+=("${include_manifest}")
-      CDISTSOURCE "$include_manifest"
+      if [[ "${run_type}" == "once" ]]; then
+         SOURCESTACKONCE+=("${include_manifest}")
+      fi
+      cdist_source "$include_manifest"
    else
       return 1
    fi
@@ -73,109 +86,126 @@ include() {
 # Safe include function for manifests including other manifests, once per host
 include_once() {
    include "${1}" once
-   return "$?"
+   return $?
 }
 
-# parse configuration file
+# Parse configuration file
 include_cfg() {
    local repo="$1"; shift
    local key="$1"; shift
-   local line include
+   local line
 
    # Find configuration file
    include_find_cfg() {
       local i key init=0
-      test "$1" == "--init" && { init=1; shift; }
+      if [[ "$1" == "--init" ]]; then
+         init=1
+         shift
+      fi
       key="$1"
-      for i in ${!_includedirs[*]}; do
-         test -f "${_includedirs[$i]}/${key}" && {
-            _cfgfile="${_includedirs[$i]}/${key}"; break; }
-         test "$init" = "1" && unset '_includedirs[i]'
+      for i in "${!_includedirs[@]}"; do
+         if [[ -f "${_includedirs[$i]}/${key}" ]]; then
+            _cfgfile="${_includedirs[$i]}/${key}"; break
+         fi
+         [[ "$init" -eq 1 ]] && unset '_includedirs[i]'
       done
-      test "$init" -eq 1 && unset '_includedirs[i]'
-      test "$_cfgfile" = "" && return 1
+      [[ "$init" -eq 1 ]] && unset '_includedirs[i]'
+      [[ -z "${_cfgfile:-}" ]] && return 1
       return 0
    }
 
-   test "${#FUNCNAME[*]}" -gt 10 && { echo "Include depth too great." > /dev/stderr;
-                                      return 1 ;}
+   if [[ "${#FUNCNAME[@]}" -gt 10 ]]; then
+      echo "Include depth too great." >&2
+      return 1
+   fi
+
    unset _cfgfile
-   if test "${FUNCNAME[0]}" != "${FUNCNAME[1]}"; then
+   if [[ "${FUNCNAME[0]}" != "${FUNCNAME[1]:-}" ]]; then
       _includedirs=( "$@" )
       include_find_cfg --init "$key"
    else
       include_find_cfg "$key"
    fi
-   test "$?" -ne 0 && return
+   [[ $? -ne 0 ]] && return
 
    while read -r -u 5 line; do
       key="${line:1}"
       case "${line:0:1}" in
-
-      @) include_cfg "$repo" "$key"
-         test "$?" -ne 0 && { echo "Error processing include $key" > /dev/stderr;
-                              return 1; }
-      ;;
-      !) if test -f "${repo}/${line:1}"; then
-            echo "${line:1}"
-         else
-            echo "File $line does not exist (from $_cfgfile)" > /dev/stderr
-            return 1
-         fi
-      ;;
+         @) include_cfg "$repo" "$key" || { echo "Error processing include $key" >&2; return 1; }
+         ;;
+         !) if [[ -f "${repo}/${line:1}" ]]; then
+               echo "${line:1}"
+            else
+               echo "File $line does not exist (from $_cfgfile)" >&2
+               return 1
+            fi
+         ;;
       esac
-   done 5< "$_cfgfile"
+   done 5< "${_cfgfile:-/dev/null}"
    return 0
 }
 
 # Pull explorer information into environment
 for explorerfile in "$__global"/explorer/*; do
-   explorer="${explorerfile/*\//}"
+   [[ -e "$explorerfile" ]] || continue
+   explorer="${explorerfile##*/}"
    explorer="${explorer//-/_}"
-   if test "$( wc -l < "$explorerfile" )" -eq 1; then
-      declare "e_$explorer=$(cat "$explorerfile")"
+
+   if [[ "$(wc -l < "$explorerfile")" -eq 1 ]]; then
+      declare "e_$explorer=$(< "$explorerfile")"
    else
       readarray -t "e_$explorer" < "$explorerfile"
    fi
 done
 
 # Always need fqdn to be set
-test "$e_fqdn" = "" && { echo "fqdn not set, aborting."; exit 1; }
-test "$e_fqdn" == "${e_fqdn%%.*}" && { echo "fqdn is not fully qualified, aborting."; exit 1; }
+if [[ -z "${e_fqdn:-}" ]]; then
+   echo "fqdn not set, aborting." >&2
+   exit 1
+fi
+
+if [[ "$e_fqdn" == "${e_fqdn%%.*}" ]]; then
+   echo "fqdn is not fully qualified, aborting." >&2
+   exit 1
+fi
 
 # Set all tags to 0
-for tag in $(cdist inventory list  | sed -n "s/.* //; s/,/\n/gp" | sort -u); do
+for tag in $(cdist inventory list | sed -n "s/.* //; s/,/\n/gp" | sort -u); do
    tag="${tag//-/_}"
    declare "t_$tag=0"
 done
+
 # Set host tags to 1
 for tag in $(cdist inventory list "$e_fqdn" | sed -n "s/.* //; s/,/ /gp" ); do
-   tag=${tag//-/_}
+   tag="${tag//-/_}"
    declare "t_$tag=1"
 done
 
-# Save explorer output
-rm -rf "${CDIST_EXPLORE:?}/$e_fqdn"; mkdir -p "$CDIST_EXPLORE/$e_fqdn"
+# Save explorer output safely
+rm -rf "${CDIST_EXPLORE:?}/$e_fqdn"
+mkdir -p "$CDIST_EXPLORE/$e_fqdn"
 for name in "$__global"/explorer/*; do
+   [[ -e "$name" ]] || continue
    cp "$name" "$CDIST_EXPLORE/$e_fqdn"
 done
 
 # Run specific manifest(s) if required. "none" will only explore.
-if test "$CDISTACTION" != ""; then
-   test "$CDISTACTION" = "none" && exit 0
+if [[ -n "${CDISTACTION:-}" ]]; then
+   [[ "$CDISTACTION" == "none" ]] && exit 0
    for manifest in ${CDISTACTION//,/ }; do
-      if test -f "$__manifest/$manifest"; then
-         CDISTSOURCE "$__manifest/$manifest"
-      elif test -f "$__manifest/$MANIFESTALL/$manifest"; then
-         CDISTSOURCE "$__manifest/$MANIFESTALL/$manifest"
+      if [[ -f "$__manifest/$manifest" ]]; then
+         cdist_source "$__manifest/$manifest"
+      elif [[ -f "$__manifest/$MANIFESTALL/$manifest" ]]; then
+         cdist_source "$__manifest/$MANIFESTALL/$manifest"
       else
-         echo "Manifest $manifest not found."
+         echo "Manifest $manifest not found." >&2
          exit 1
       fi
    done
-   exit
+   exit 0
 fi
 
 for manifest in "$__manifest"/"$MANIFESTALL"/*; do
-  CDISTSOURCE "$manifest"
+   [[ -e "$manifest" ]] || continue
+   cdist_source "$manifest"
 done
